### ISSUE TITLE
Why only std::shared_ptr ?

### ISSUE THREAD

**Issue by Ravirael** [skypjack/eventpp#1]
I like the event bus idea, however does it really need to depend on `std::shared_ptr`? It makes it difficult to integrate event bus in projects which do not use shared ownership and therefore shared pointers. I think that it should be possible to register listner via raw pointer, provided that it unregisters itself in destructor or even before its destructor is called.

**Comment by skypjack** [comment]
I'm planning to create a new project that has buses for both the models.
The advantage of the one using `shared_ptr`s is that you don't have to care about the lifetime of your listeners, they are automatically removed from the base when expired (note that the bus stores a `weak_ptr`, not a `shared_ptr`).
In the other case, you have to manage explicitly that situation, so dangling pointers quickly become a risk.
Anyway, I'd suggest to stay tuned, for the new, minimal project is coming and it contains delegates, as well as observers defined the way you would like them to be defined, as well as the event bus defined the way it's defined, and so on...

**Comment by skypjack** [comment]
@Ravirael 
Well, ok, it took me a while to start the new project to which I was thinking.
However, finally here it is. The signalling stuff I promised is part of [`EnTT`](https://github.com/skypjack/entt).
Hope you can find there all what you are looking for.
